combos:
  - name: "Starter : Rotary (Full Combo)"
    requirements:
      - name: "Kewl Tune Rotary"
        count: 1
        
  - name: "Starter : Reco (Full Combo)"
    requirements:
      - name: "Kewl Tune Reco"
        count: 1
        
  - name: "Starter : Field Spell (JJ)"
    requirements:
      - name: 'JJ "Kewl Tune"'
        count: 1
        
  - name: "Starter : Synchro Overtake"
    requirements:
      - name: "Synchro Overtake"
        count: 1

  - name: "God Hand: Combo + Anti-Handtrap"
    requirements:
      - name: "Kewl Tune Rotary"
        count: 1
      - name: "Called by the Grave"
        count: 1
